---
  - hosts: lmilbaum-contra-sample

    tasks:
      - name: Check if vim pkg installed
        command: rpm -q vim-enhanced
        register: result
        always_run: yes
        
      - name: Assert result.rc = 0
        assert:
          that:
            - "result.rc == 0"
